# Generated by Django 3.1.3 on 2020-12-06 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerB',
            new_name='Player_A',
        ),
        migrations.RenameModel(
            old_name='PlayerA',
            new_name='Player_B',
        ),
        migrations.RenameField(
            model_name='player_a',
            old_name='answer',
            new_name='answerA',
        ),
        migrations.RenameField(
            model_name='player_a',
            old_name='hint',
            new_name='hintA',
        ),
        migrations.RenameField(
            model_name='player_a',
            old_name='option1',
            new_name='option1A',
        ),
        migrations.RenameField(
            model_name='player_a',
            old_name='option2',
            new_name='option2A',
        ),
        migrations.RenameField(
            model_name='player_a',
            old_name='option3',
            new_name='option3A',
        ),
        migrations.RenameField(
            model_name='player_a',
            old_name='option4',
            new_name='option4A',
        ),
        migrations.RenameField(
            model_name='player_a',
            old_name='questionB',
            new_name='questionA',
        ),
        migrations.RenameField(
            model_name='player_b',
            old_name='answer',
            new_name='answerB',
        ),
        migrations.RenameField(
            model_name='player_b',
            old_name='hint',
            new_name='hintB',
        ),
        migrations.RenameField(
            model_name='player_b',
            old_name='option1',
            new_name='option1B',
        ),
        migrations.RenameField(
            model_name='player_b',
            old_name='option2',
            new_name='option2B',
        ),
        migrations.RenameField(
            model_name='player_b',
            old_name='option3',
            new_name='option3B',
        ),
        migrations.RenameField(
            model_name='player_b',
            old_name='option4',
            new_name='option4B',
        ),
        migrations.RenameField(
            model_name='player_b',
            old_name='questionA',
            new_name='questionB',
        ),
    ]
