# Generated by Django 3.1.3 on 2020-12-08 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201206_1151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player_A',
        ),
        migrations.DeleteModel(
            name='Player_B',
        ),
    ]
