# Generated by Django 3.1.3 on 2020-12-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201208_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_A', models.CharField(max_length=500)),
                ('option1_A', models.CharField(max_length=100)),
                ('option2_A', models.CharField(max_length=100)),
                ('option3_A', models.CharField(max_length=100)),
                ('option4_A', models.CharField(max_length=100)),
                ('hint_A', models.CharField(max_length=300)),
                ('answer_A', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team_B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_B', models.CharField(max_length=500)),
                ('option1_B', models.CharField(max_length=100)),
                ('option2_B', models.CharField(max_length=100)),
                ('option3_B', models.CharField(max_length=100)),
                ('option4_B', models.CharField(max_length=100)),
                ('hint_B', models.CharField(max_length=300)),
                ('answer_B', models.CharField(max_length=100)),
            ],
        ),
    ]
